### ISSUE TITLE
Support for 5.4 requested

### ISSUE THREAD

**Issue by nusphere** [SonarQubeCommunity/sonar-issues-report#3]
It would be nice to support the latest LTS Version

**Comment by julienlancelot** [comment]
Sorry, but this plugin is deprecated since SonarQube 5.1 : http://docs.sonarqube.org/display/PLUG/Issues+Report+Plugin.

Because using SonarLint, you get better and quicker feedbacks !

Why would you want to use this plugin ?

**Comment by nusphere** [comment]
thx you for this hint. sorry for this issue :) should be closed
